### ISSUE TITLE
Kilo branch

### ISSUE THREAD

**Issue by badmutex** [openstack-ansible-galaxy/openstack-keystone#2]
I've been working on adapting this role to deploy the Kilo version of Keystone and will be submitting a PR. Should it go into the development branch or a special feature branch to-be-created?

**Comment by dguerri** [comment]
I have just created a kilo branch. Feel free to submit the PR against this!

**Comment by badmutex** [comment]
Excellent. You should see it come in middle of next week.
Thanks!
